### ISSUE TITLE
please push 1.0.3 gem

### ISSUE THREAD

**Issue by jkraemer** [envato/safe_shell#7]
Hi,

I'd like my pdf-forms gem to depend on 1.0.3 for the JRuby support. Any chance for a gem release soon or is there something holding you back?

Thanks,
Jens

**Comment by joneslee85** [comment]
@jkraemer sure, I'll try to get it sorted.

**Comment by joneslee85** [comment]
cc @notahat

**Comment by Ch4s3** [comment]
:+1:

**Comment by joneslee85** [comment]
https://rubygems.org/gems/safe_shell/versions/1.0.3
